### ISSUE TITLE
点击相册选择，怎么配置能打开选择相片的界面，如图3所示界面。现在点击打开的是图2所示界面

### ISSUE THREAD

**Issue by hdjhdjhdj** [hjfruit/react-native-upload2#10]
图1
![image](https://github.com/user-attachments/assets/d254e7ff-0496-48be-a04c-7cafb87876a0)
图2
![image](https://github.com/user-attachments/assets/e646bc48-46ec-4f56-81da-6edbfa345db6)
图3
![image](https://github.com/user-attachments/assets/9c5bff9e-380e-4820-9279-b595ae98d0aa)

**Comment by Limoer96** [comment]
查看了上游依赖[react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker)，发现其并不支持直接打开相册而是打开文件选择器，再根据`mediaType`去设置选择器类型。所以`openPicker`打开图二是预期之内的，[见实现](https://github.com/ivpusic/react-native-image-crop-picker/blob/5333954ae411da4c9e948ea6658ab414e66ed211/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L359-L386)。

如果你要想直接打开相册，可以尝试按照[这个PR](https://github.com/ivpusic/react-native-image-crop-picker/pull/1156)来修改。

**Comment by hdjhdjhdj** [comment]
感谢大佬，这样会好点。
这些库我都是最新版本的，我去那边提下，这么多年都不加个参数可以给人配置。
