### ISSUE TITLE
您好，请问我装了库以及依赖库，在运行的时候出现问题了。

### ISSUE THREAD

**Issue by qianshihoushi** [hjfruit/react-native-upload2#7]
我安装依赖react-native-photo-manipulator库后，提示因为这个库构建失败，我的react-native：0.72.3，我看了下你们example里面的版本也是在.7以后的，不知道你们遇到这个问题了吗？react-native-photo-manipulator库都是1.2.7版本的

**Comment by Limoer96** [comment]
经尝试在RN0.71版本中的项目中iOS和Android都没有遇到构建失败的问题。请问你是哪个平台构建失败的，具体的错误信息？我可以帮你排查下。

**Comment by qianshihoushi** [comment]
> 经尝试在 RN0.71 版本中的项目中 iOS 和 Android 都没有遇到构建失败的问题。请问你是哪个平台构建失败的，具体的错误信息？我可以帮你排查下。

您好，我目前使用的Android的项目，具体的信息如下 :
![image](https://github.com/hjfruit/react-native-upload2/assets/59005729/706e0635-7cbf-47c5-8487-f9bad10c0490)

**Comment by Limoer96** [comment]
> > 经尝试在 RN0.71 版本中的项目中 iOS 和 Android 都没有遇到构建失败的问题。请问你是哪个平台构建失败的，具体的错误信息？我可以帮你排查下。
> 
> 您好，我目前使用的Android的项目，具体的信息如下 : ![image](https://user-images.githubusercontent.com/59005729/267885386-706e0635-7cbf-47c5-8487-f9bad10c0490.png)

这是因为该原生模块以及其它的部分模块是`kotlin`编写的，你需要在`android/build.gradle`文件中的`buildscript.ext`中指定`kotlinVersion`，例如:

```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        kotlinVersion = "1.7.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33

        ndkVersion = "23.1.7779620"
    }
}
```

**Comment by qianshihoushi** [comment]
> > > 经尝试在 RN0.71 版本中的项目中 iOS 和 Android 都没有遇到构建失败的问题。请问你是哪个平台构建失败的，具体的错误信息？我可以帮你排查下。
> > 
> > 
> > 您好，我目前使用的Android的项目，具体的信息如下 : ![image](https://user-images.githubusercontent.com/59005729/267885386-706e0635-7cbf-47c5-8487-f9bad10c0490.png)
> 
> 这是因为该原生模块以及其它的部分模块是`kotlin`编写的，你需要在`android/build.gradle`文件中的`buildscript.ext`中指定`kotlinVersion`，例如:
> 
> ```
> buildscript {
>     ext {
>         buildToolsVersion = "33.0.0"
>         kotlinVersion = "1.7.0"
>         minSdkVersion = 23
>         compileSdkVersion = 33
>         targetSdkVersion = 33
> 
>         ndkVersion = "23.1.7779620"
>     }
> }
> ```

非常感谢您的帮助，问题解决了，谢谢了。
