### ISSUE TITLE
大佬，有个问题 上传图片的问题请教一下。

### ISSUE THREAD

**Issue by qianshihoushi** [hjfruit/react-native-upload2#8]
我通过 react-native-image-crop-picker 这个库 拍的照片，然后进行 使用 fetch API，formData 对象发送文件，就是有的手机，会在 fetch 的 catch 方法中捕获到错误，但是后端说他没有收到请求。就不知道这个错误的信息是哪里来的？ 想请问下大佬，应该怎么做？？

**Comment by Limoer96** [comment]
你好，请提供你具体的出错信息、RN版本和设备信息，我帮你排查一下。

**Comment by qianshihoushi** [comment]
> 你好，请提供你具体的出错信息、RN版本和设备信息，我帮你排查一下。

RN 版本为 ： 0.72.3,
设备是小米10s手机，别的手机倒是没遇到,
现在使用 axios 进行formData 上传 ，
报错 信息： 
`{
  "message": "Network Error",
  "name": "AxiosError",
  "stack": "AxiosError: Network Error\\n    at handleError (address at index.android.bundle:1:650778)\\n    at call (native)\\n    at dispatchEvent (address at index.android.bundle:1:207473)\\n    at setReadyState (address at index.android.bundle:1:198920)\\n    at __didCompleteResponse (address at index.android.bundle:1:196570)\\n    at apply (native)\\n    at anonymous (address at index.android.bundle:1:198525)\\n    at apply (native)\\n    at emit (address at index.android.bundle:1:68375)\\n    at apply (native)\\n    at __callFunction (address at index.android.bundle:1:77059)\\n    at anonymous (address at index.android.bundle:1:75416)\\n    at __guard (address at index.android.bundle:1:76366)\\n    at callFunctionReturnFlushedQueue (address at index.android.bundle:1:75374)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": ["xhr", "http"],
    "transformRequest": [null],
    "transformResponse": [null],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "multipart/form-data",
      "token": "O7hbNjinHvPzkQ6izkDxjJWhpR0gTF62",
      "Userid": "109"
    },
    "method": "post",
    "url": "xxx", // 上传地址
    "data": {
      "_parts": [
        ["location", "xxxx · xxxx"],
        ["orderID", 647],
        ["content", ""],
        [
          "file",
          {
            "uri": "file:///storage/emulated/0/Android/data/com.testapp/files/Pictures/eb0cefbc-2665-48e2-bdcb-860a9a2ccb99.jpg",
            "type": "image/jpeg",
            "name": "image.jpg"
          }
        ]
      ]
    }
  },
  "code": "ERR_NETWORK",
  "status": null
}
`

**Comment by Limoer96** [comment]
@lijinglun123 你可以尝试以下方式，看问题能否解决：

- 尝试把`axios`降级到`0.27.x`
- 尝试使用RN自带的`fetch`API
- 如果你使用的是`http`协议，请检查是否在`AndroidManifest.xml`中配置了`networkSecurityConfig`

**Comment by qianshihoushi** [comment]
> @lijinglun123 你可以尝试以下方式，看问题能否解决：
> 
> * 尝试把`axios`降级到`0.27.x`
> * 尝试使用RN自带的`fetch`API
> * 如果你使用的是`http`协议，请检查是否在`AndroidManifest.xml`中配置了`networkSecurityConfig`

谢谢您了，我获取了图片的base64，传给后端了。
