### ISSUE TITLE
大佬，有个问题。想控制上传的格式，要怎么操作？如只能上传图片，只能上传视频，只能上传jpg图片。类似这样的

### ISSUE THREAD

**Issue by hdjhdjhdj** [hjfruit/react-native-upload2#9]

**Comment by Limoer96** [comment]
如果你设置`pickerType=cropPicker`，表示使用选择器来上传文件，此时可以通过设置`cropPickerMediaType`为`photo | video`来限制选择器只能选到图片/视频。

该组件暂不支持指定特定类型的图片/视频。

**Comment by hdjhdjhdj** [comment]
> 如果你设置`pickerType=cropPicker`，表示使用选择器来上传文件，此时可以通过设置`cropPickerMediaType`为`photo | video`来限制选择器只能选到图片/视频。
> 
> 该组件暂不支持指定特定类型的图片/视频。

感谢解答
